-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgUERhUVkqFKv8yREh
vKGvRPYXP1fCpb1mq+j0LZFDmTOgCgYIKoZIzj0DAQehRANCAAQL6wZx6gat8RXA
1flGneDt9CW/nEHG4x8eu+s1MLZlO5dydU2sCcTurWO+UNKH3Tb3iTAWcF9MGAwA
moZgJvjp
-----END PRIVATE KEY-----